#!/usr/bin/env python
# encoding: utf-8

import sys
import os
import diststore
from socket import *
import struct
import fcntl

def get_ip_address(ifname):
	"""Get address for `ifname`.  Linux only."""
	s = socket(AF_INET, SOCK_STREAM)
	return inet_ntoa(fcntl.ioctl(s.fileno(), 0x8915, struct.pack('256s', ifname[:15]))[20:24])

def main():
    print "diststored starting"
    addr = ''
    possible_interfaces = ["eth0", "en1", "en0"]
    for interface in possible_interfaces:
        try:
    	    addr = get_ip_address(interface)
	    print "Using interface %s, ip %s" % (interface, addr)
        except IOError:
	    pass
	if addr != '':
	    break
    try:
        server = diststore.Server(ip=addr)
        server.start()
    except:
        print "diststored terminated"
if __name__ == '__main__':
    main()

