#!/usr/bin/env python
# encoding: utf-8

import sys
import os
import diststore

def main():
    print "diststored starting"
    try:
        server = diststore.Server()
        server.start()
    except:
        print "diststored terminated"
if __name__ == '__main__':
    main()

