Document: pydiststore
Title: Debian pydiststore Manual
Author: <insert document author here>
Abstract: This manual describes what pydiststore is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pydiststore/pydiststore.sgml.gz

Format: postscript
Files: /usr/share/doc/pydiststore/pydiststore.ps.gz

Format: text
Files: /usr/share/doc/pydiststore/pydiststore.text.gz

Format: HTML
Index: /usr/share/doc/pydiststore/html/index.html
Files: /usr/share/doc/pydiststore/html/*.html


